import type { Metadata } from "next";
import { Alfa_Slab_One, Chivo, Chivo_Mono } from "next/font/google";
import "./globals.css";

const alfaSlabOneSerif = Alfa_Slab_One({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["400"],
});

const chivoSans = Chivo({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const chivoMono = Chivo_Mono({
  variable: "--font-mono",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alfaSlabOneSerif.variable} ${chivoSans.variable} ${chivoMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
